# Try to include optional files. Any settings in these files override the main settings.
IncludeOptional:
    # Secure Kafka settings
    - news_secret.yml
General:
    # Maximum number of sessions that can be open in the simulator at the same time
    maxSessions: 50000
    minSleep: 0.00001
    maxSleep: 0.00004
    # clickTopic and sessionTopic can be the same
    clickTopic: "imply-news"
    sessionTopic: "imply-news"
Kafka:
    bootstrap.servers: 'b-1.se-demo-msk.9ar7z6.c4.kafka.us-east-1.amazonaws.com'
StateMachine:
    States: [ 'home', 'content', 'clickbait', 'subscribe', 'plusContent', 'affiliateLink', 'exitSession' ]
    # exitState: 'exitSession'
    # -- no need to specify the exit state explicitly; any state that does not exist as a row key in the transition matrix is an exit state
    StateTransitionMatrix:
        # Transition probabilities. For each mode there is a separate transition matrix. Probabilities in each row must add up to 1.
        default: {
            'home':          { 'home': 0.10, 'content': 0.30, 'clickbait': 0.06, 'subscribe': 0.000, 'plusContent': 0.20, 'affiliateLink': 0.02, 'exitSession': 0.32 },
            'content':       { 'home': 0.15, 'content': 0.45, 'clickbait': 0.06, 'subscribe': 0.002, 'plusContent': 0.20, 'affiliateLink': 0.02, 'exitSession': 0.118 },
            'clickbait':     { 'home': 0.10, 'content': 0.10, 'clickbait': 0.50, 'subscribe': 0.000, 'plusContent': 0.16, 'affiliateLink': 0.02, 'exitSession': 0.12 },
            'subscribe':     { 'home': 0.10, 'content': 0.20, 'clickbait': 0.00, 'subscribe': 0.000, 'plusContent': 0.50, 'affiliateLink': 0.02, 'exitSession': 0.18 },
            'plusContent':   { 'home': 0.10, 'content': 0.30, 'clickbait': 0.06, 'subscribe': 0.002, 'plusContent': 0.40, 'affiliateLink': 0.02, 'exitSession': 0.118 },
            'affiliateLink': { 'home': 0.20, 'content': 0.20, 'clickbait': 0.00, 'subscribe': 0.000, 'plusContent': 0.05, 'affiliateLink': 0.00, 'exitSession': 0.55 }
        }
        special: {
            'home':          { 'home': 0.10, 'content': 0.30, 'clickbait': 0.06, 'subscribe': 0.000,  'plusContent': 0.26, 'affiliateLink': 0.02, 'exitSession': 0.26 },
            'content':       { 'home': 0.15, 'content': 0.45, 'clickbait': 0.06, 'subscribe': 0.0005, 'plusContent': 0.20, 'affiliateLink': 0.02, 'exitSession': 0.1195 },
            'clickbait':     { 'home': 0.10, 'content': 0.10, 'clickbait': 0.50, 'subscribe': 0.000,  'plusContent': 0.16, 'affiliateLink': 0.02, 'exitSession': 0.12 },
            'subscribe':     { 'home': 0.10, 'content': 0.20, 'clickbait': 0.00, 'subscribe': 0.000,  'plusContent': 0.50, 'affiliateLink': 0.02, 'exitSession': 0.18 },
            'plusContent':   { 'home': 0.10, 'content': 0.30, 'clickbait': 0.06, 'subscribe': 0.0005, 'plusContent': 0.40, 'affiliateLink': 0.02, 'exitSession': 0.1195 },
            'affiliateLink': { 'home': 0.20, 'content': 0.20, 'clickbait': 0.00, 'subscribe': 0.000,  'plusContent': 0.05, 'affiliateLink': 0.00, 'exitSession': 0.55 }
        }
