# Try to include optional files. Any settings in these files override the main settings.
# Not implemented yet
IncludeOptional:
    # Secure Kafka settings
    - news_secret.yml
General:
    # topice can be the same
    newTopic: "bets-new"
    cancellationTopic: "bets-cancellations"
Kafka:
    bootstrap.servers: '34.209.28.189:9092'

